// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5G8Sf0hiwr60bql9zASHS58hhGA9gHNI',
    appId: '1:842364766534:web:7a7c9e2e641a70321dbd47',
    messagingSenderId: '842364766534',
    projectId: 'photoclass-462a2',
    authDomain: 'photoclass-462a2.firebaseapp.com',
    storageBucket: 'photoclass-462a2.appspot.com',
    measurementId: 'G-3MV4SXJ21R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDClcRqZpa0t6F2OsEulgar4Vbd2U8N9C0',
    appId: '1:842364766534:android:c87a4f67cc6a34801dbd47',
    messagingSenderId: '842364766534',
    projectId: 'photoclass-462a2',
    storageBucket: 'photoclass-462a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCohh3eeKABUnRQBzMu-vBBGte_XXC33uQ',
    appId: '1:842364766534:ios:fee7ba789355e2381dbd47',
    messagingSenderId: '842364766534',
    projectId: 'photoclass-462a2',
    storageBucket: 'photoclass-462a2.appspot.com',
    iosClientId: '842364766534-nge6sss9rjv6l59852u1dtejmmf7v0h6.apps.googleusercontent.com',
    iosBundleId: 'com.example.photoclass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCohh3eeKABUnRQBzMu-vBBGte_XXC33uQ',
    appId: '1:842364766534:ios:fee7ba789355e2381dbd47',
    messagingSenderId: '842364766534',
    projectId: 'photoclass-462a2',
    storageBucket: 'photoclass-462a2.appspot.com',
    iosClientId: '842364766534-nge6sss9rjv6l59852u1dtejmmf7v0h6.apps.googleusercontent.com',
    iosBundleId: 'com.example.photoclass',
  );
}
